#!/usr/bin/env bash

set -euo pipefail

function get_pipeline() {
  # To dont spit to stdout pulling logs
  docker pull docker.io/evalsocket/rollback-buildkite-plugin:0.0.1 > /dev/null

  docker run --rm \
    -e BUILDKITE_API_TOKEN \
    -e BUILDKITE_PLUGIN_ROLLBACK_NAME \
    docker.io/evalsocket/rollback-buildkite-plugin:0.1.1 \
}

rollback="false"
if [ $BUILDKITE_COMMAND_EXIT_STATUS != 0 ]; then
  rollback="true"
  pipeline=$(get_pipeline)
  if [ -n "$pipeline" ]; then
    echo "Uploading new pipeline"
    echo "$pipeline"
    echo "$pipeline" | echo
  fi
fi

