#!/usr/bin/env bash

set -euo pipefail

function get_pipeline() {
	go run main.go
}

if [ $BUILDKITE_COMMAND_EXIT_STATUS != 0 ]; then
  pipeline=$(get_pipeline)
  if [ -n "$pipeline" ]; then
    echo "Uploading new pipeline"
    echo "$pipeline"
    echo "$pipeline" | buildkite-agent pipeline upload
  fi
fi
